<?php

namespace AppBundle\Repository;

/**
 * ChangePwdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangePwdRepository extends \Doctrine\ORM\EntityRepository
{
}
