<?php

namespace AppBundle\Repository;

/**
 * NotificationSystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationSystemRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByUser($userTarget) {
        $qb = $this
            ->createQueryBuilder('u')
            ->setParameter('idTarget', $userTarget)
            ->where('u.idTarget=:idTarget')
            ->getQuery();
        return $qb->getResult();
    }

}
