<?php

namespace AppBundle\Repository;

/**
 * ThreadWaitingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadWaitingRepository extends \Doctrine\ORM\EntityRepository
{
}
