<?php

namespace AppBundle\Repository;

/**
 * ThreadWaitingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadWaitingRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return array
     */
    public function findOlders() {
        $now = new \DateTime('now');
        $qb = $this
            ->createQueryBuilder('w')
            ->where('w.istrait < 1')
            ->orderBy('w.datesend')
            ->getQuery();
        return $qb->getResult();
    }

    /**
     * @param $idComp
     * @return array
     */
    public function findByIdComp($idComp) {
        $qb = $this
            ->createQueryBuilder('tw')
            ->setParameter('id', $idComp)
            ->where('tw.idcomp=:id')
            ->getQuery();
        return $qb->getResult();
    }

}
