<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjectsInCompany($companyId) {
        $qb = $this
            ->createQueryBuilder('u')
            ->join('u.authorProject', 'p')
            ->setParameter('idCompany', $companyId)
            ->where('u.company=:idCompany')
            ->getQuery();
        return $qb->getResult();
    }

    public function getUser() {
        $qb = $this
            ->createQueryBuilder('u')
            ->join('u.company', 'c')
            ->where('u.status = 2 or u.status = 3')
            ->getQuery();
        return $qb->getResult();
    }

    public function getHappyCoach() {
        $qb = $this
            ->createQueryBuilder('u')
            ->where('u.status = 4')
            ->getQuery();
        return $qb->getResult();
    }
}
