<?php

namespace AppBundle\Repository;

/**
 * UserHasSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserHasSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
